/**
 * Pure, platform-free layout primitives shared across the Darkness family.
 *
 * Hosts on the JVM (termtastic's server) and on Kotlin/JS (notegrow's web
 * shell, the toolkit's renderer) both need to compute the same pane
 * geometry, so the [LayoutPreset] enum, the [LayoutBox] rectangle type,
 * the [PaneId] alias, and the [GridSpec] snapping helper live in
 * commonMain. The toolkit's web layer adds rendering (`LayoutRenderer`,
 * miniature SVG previews) on top; nothing in this file depends on a
 * particular runtime.
 *
 * The package name is kept as `se.soderbjorn.darkness.web.layout` for
 * source compatibility with consumers that imported these types when
 * they lived in the toolkit-web module.
 *
 * @see GridSpec
 * @see LayoutPreset
 * @see LayoutBox
 */
package se.soderbjorn.darkness.web.layout

/**
 * Stable identifier for a pane. Generated by callers — typically a UUID
 * or a counter-prefixed string. The toolkit treats it opaquely.
 */
typealias PaneId = String

/**
 * Rectangle in normalized layout space. Both [x],[y] and [width],[height]
 * are in `(0.0, 1.0)`. The toolkit's miniature renderer scales these to a
 * pixel viewBox; layout-apply consumers assign them to each pane's
 * `xPct/yPct/widthPct/heightPct`.
 *
 * @property x      left edge in normalized space
 * @property y      top edge in normalized space
 * @property width  width in normalized space
 * @property height height in normalized space
 */
data class LayoutBox(
    val x: Double,
    val y: Double,
    val width: Double,
    val height: Double,
)

/**
 * Describes the snap grid the host expects pane positions and sizes to
 * align to. Both [LayoutPreset.Auto] and the toolkit's drag-to-move /
 * drag-to-resize gestures quantize their output to this grid so
 * auto-tiled panes are visually indistinguishable from hand-placed ones.
 *
 * The grid is owned by the host app — termtastic and notegrow may pick
 * different resolutions — and is passed in whenever a layout is computed
 * or a pane is moved/resized. A `null` or "no-grid" caller can pass
 * `GridSpec.NONE` to opt out of snapping.
 *
 * Coordinates and sizes are normalized to `[0.0, 1.0]` and a "grid line"
 * is at every `i / cols` (for x) or `i / rows` (for y) for `i in 0..N`.
 *
 * @property cols  number of vertical grid lines across the canvas; the
 *   horizontal cell width is `1.0 / cols`. `1` disables horizontal snap.
 * @property rows  number of horizontal grid lines down the canvas; the
 *   vertical cell height is `1.0 / rows`. `1` disables vertical snap.
 *
 * @see snap
 * @see LayoutPreset.Auto
 */
data class GridSpec(
    val cols: Int,
    val rows: Int,
) {
    init {
        require(cols >= 1) { "cols must be >= 1, got $cols" }
        require(rows >= 1) { "rows must be >= 1, got $rows" }
    }

    /** Width of a single grid cell in normalized space. */
    val cellWidth: Double get() = 1.0 / cols

    /** Height of a single grid cell in normalized space. */
    val cellHeight: Double get() = 1.0 / rows

    /**
     * Snaps a single coordinate to the nearest grid line. Used by
     * drag-to-move handlers; layout presets typically snap whole
     * rectangles via [snapBox].
     *
     * @param value coordinate in `[0.0, 1.0]`.
     * @param horizontal `true` to snap against [cols] (x axis),
     *   `false` to snap against [rows] (y axis).
     * @return the input rounded to the nearest grid line.
     */
    fun snap(value: Double, horizontal: Boolean): Double {
        val divisions = if (horizontal) cols else rows
        if (divisions <= 1) return value.coerceIn(0.0, 1.0)
        val raw = (value * divisions).fastRound()
        return (raw.toDouble() / divisions).coerceIn(0.0, 1.0)
    }

    /**
     * Snaps a rectangle to the grid by snapping the four edges
     * independently. The result has integer cell-line edges and cell
     * sizes; it never has zero width or height (clamped to one cell).
     *
     * Used by [LayoutPreset.Auto] when quantizing fractional splits and
     * by drag-to-resize handlers.
     *
     * @param box rectangle to snap.
     * @return a new [LayoutBox] with grid-aligned edges.
     */
    fun snapBox(box: LayoutBox): LayoutBox {
        val left = snap(box.x, horizontal = true)
        val top = snap(box.y, horizontal = false)
        var right = snap(box.x + box.width, horizontal = true)
        var bottom = snap(box.y + box.height, horizontal = false)
        if (right <= left) right = (left + cellWidth).coerceAtMost(1.0)
        if (bottom <= top) bottom = (top + cellHeight).coerceAtMost(1.0)
        return LayoutBox(left, top, right - left, bottom - top)
    }

    companion object {
        /**
         * No-op grid: every coordinate is its own grid line. Use when a
         * caller hasn't opted into snapping (e.g. the dropdown's
         * miniature SVG preview, which renders sub-pixel boxes).
         */
        val NONE: GridSpec = GridSpec(cols = 1, rows = 1)
    }
}

/**
 * Toolkit-owned default snap grid for the auto-tile preset, every
 * preset apply, and the manual drag/resize gestures. A 20×20 grid puts
 * the cell width at 5 % of the canvas — fine enough to feel continuous
 * yet coarse enough that hand-placed and auto-placed panes share visible
 * edges.
 *
 * Mirrors notegrow's pre-refactor `AUTO_LAYOUT_GRID` so the visual result
 * is unchanged. Not configurable per app today — the Darkness family
 * shares a single chrome (`feedback_no_chrome_variants`); if a future app
 * legitimately needs another resolution we can expose it through
 * `AppShellSpec`.
 */
val DEFAULT_LAYOUT_GRID: GridSpec = GridSpec(cols = 20, rows = 20)

/** Banker's-rounding-free helper to round a Double to the nearest Long. */
private fun Double.fastRound(): Long = (this + if (this >= 0.0) 0.5 else -0.5).toLong()

/**
 * Built-in pane arrangements offered by the toolkit's "Layout" dropdown.
 *
 * Each preset maps an integer pane count `n` to a list of [LayoutBox]
 * rectangles via [LayoutPreset.computeBoxes]. Slot 0 is always the
 * **primary** — that's the position the active/focused pane lands in
 * when the layout is applied, and the slot the dropdown miniature
 * highlights so the user can see at a glance where their active pane
 * will end up. Hosts apply the layout by reading the boxes and assigning
 * `xPct/yPct/widthPct/heightPct` to each pane.
 *
 * The set mirrors termtastic's `LayoutMenu.kt` palette so apps in the
 * Darkness family present the same options.
 *
 * [Auto] is special: it picks geometry based purely on the pane count
 * and is intended to be combined with a `LayoutController` that re-tiles
 * automatically as panes are added or removed. See `Auto.computeBoxes`
 * for the per-count geometry.
 *
 * @see LayoutPreset.computeBoxes
 * @see GridSpec
 */
enum class LayoutPreset {
    /**
     * Auto-tiling preset: the toolkit picks a sensible geometry for the
     * current pane count and re-tiles whenever panes are added, removed,
     * or focused. With a host-supplied [GridSpec] the resulting boxes
     * align to the same grid manual placement uses.
     */
    Auto,

    // Equal (size-neutral resets)
    Grid,
    Columns,
    Rows,
    // Hero: primary 65% + equal sibling strip 35%
    HeroLeft,
    HeroRight,
    HeroTop,
    HeroBottom,
    // Half-and-half: primary 50% + equal sibling strip 50%
    SplitHorizontal,
    SplitVertical,
    // Sidebar: primary 75% + thin equal sibling strip 25%
    SidebarLeft,
    SidebarRight,
    SidebarTop,
    SidebarBottom,
    // T shapes: primary + one medium on a 70/30 row, equal strip on the other
    TShape,
    TShapeInverted,
    // L shapes: primary corner + full-edge sibling + equal strip
    LShape,
    LShapeTopRight,
    LShapeBottomLeft,
    LShapeBottomRight,
    // Big primary + medium + equal stacked remainder
    BigTwoStack,
    BigTwoStackRight,
    BigTwoStackBottom,

    /**
     * Auto-style preset with **two** privileged ranks. Like [Auto] but
     * the secondary pane (slot 1) gets a privileged half of the right
     * strip; the rest equal-stack the other half. For `n=2` collapses
     * to a 60/40 split; for `n=3` the secondary fills the strip's top
     * half and the third pane fills the bottom — matching `Auto-3`'s
     * geometry. The "rest" share the bottom half once `n ≥ 4`.
     */
    AutoBigTwo,

    /** Mirror of [AutoBigTwo] — primary 60% on the **right**, secondary
     *  privileged top of the left strip, rest stacked below the secondary. */
    AutoBigTwoRight,

    /** [AutoBigTwo] rotated — primary 60% across the **top**, secondary
     *  privileged left of the bottom strip, rest tiled to its right. */
    AutoBigTwoTop,

    /** [AutoBigTwo] rotated — primary 60% across the **bottom**, secondary
     *  privileged left of the top strip, rest tiled to its right. */
    AutoBigTwoBottom,

    /**
     * Auto-style preset with **three** privileged ranks. Primary 50%
     * full-height on the left; slots 2 and 3 stacked top-right at 50%
     * × 50% each; the rest equal-distribute across the bottom-right
     * 50% × 50%. Collapses gracefully for `n < 4`.
     */
    AutoBigThree,

    /**
     * Static two-tier hero. Primary 55% × 100% on the left; secondary
     * 45% × 40% top-right; the rest equal-stack the 45% × 60% bottom
     * right. Unlike [AutoBigTwo] this preset is fixed — it does not
     * reflow geometry as panes change beyond the count adapting to
     * the rest strip; it stays sticky once applied.
     */
    HeroPair,

    /** Mirror of [HeroPair] — primary 55% on the **right**, secondary
     *  privileged top of the left strip, rest stacked below it. */
    HeroPairRight,

    /** [HeroPair] rotated — primary 55% across the **top**, secondary
     *  privileged left of the bottom strip, rest tiled to its right. */
    HeroPairTop,

    /** [HeroPair] rotated — primary 55% across the **bottom**, secondary
     *  privileged left of the top strip, rest tiled to its right. */
    HeroPairBottom,

    /**
     * Sentinel for "the user has hand-tweaked geometry — no preset is
     * driving." A `LayoutController` transitions to [Custom] whenever a
     * manual move or resize overrides preset-driven placement. Selecting
     * any other preset from the dropdown leaves [Custom] mode.
     *
     * Has no boxes of its own; [computeBoxes] returns an empty list.
     */
    Custom,
    ;

    /**
     * Computes the rectangle each pane will occupy when this preset is
     * applied to a tab containing [paneCount] panes. Box index 0 is the
     * primary slot — the active pane lands there.
     *
     * Coordinates are in `(0.0, 0.0)..(1.0, 1.0)` space; the dropdown's
     * miniature renderer scales them to its preview viewBox, and hosts
     * applying the layout assign these to each pane's
     * `xPct/yPct/widthPct/heightPct`.
     *
     * If [grid] is given (non-`null`, not `GridSpec.NONE`), each box is
     * snapped to the grid so auto-tiled panes are visually
     * indistinguishable from hand-placed, snap-aligned panes.
     *
     * @param paneCount how many panes the active tab currently contains;
     *   `0` returns an empty list, `1` collapses to a single full-bleed box.
     * @param grid optional snap grid. When `null` or [GridSpec.NONE],
     *   boxes are returned with their raw fractional coordinates.
     * @return a list of [paneCount] rectangles, slot 0 first.
     */
    fun computeBoxes(paneCount: Int, grid: GridSpec? = null): List<LayoutBox> {
        val raw = computeLayoutBoxes(this, paneCount)
        if (grid == null || grid === GridSpec.NONE) return raw
        return raw.map { grid.snapBox(it) }
    }

    /**
     * How many leading slots receive geometry meaningfully larger than
     * the equal-strip "rest" — i.e. how many ranks of `paneOrder` the
     * preset honours when applied. Drives the dropdown miniature's
     * per-rank fill so users can tell at a glance which presets respect
     * rank beyond `panes[0]`.
     *
     * Read by `renderPresetMiniatureSvg` in the toolkit's web module to
     * pick between the primary, secondary, and "other" preview classes.
     * Apps that build their own dropdown can read it the same way.
     *
     * Values: `1` for single-priority presets ([Auto], [Grid], `Hero*`,
     * `Sidebar*`, `Split*`, [Columns], [Rows]); `2` for the two-tier
     * shapes ([AutoBigTwo], [HeroPair], `BigTwoStack*`, `TShape*`,
     * `LShape*`); `3` for [AutoBigThree]. [Custom] reports `1` since it
     * has no preset-driven geometry.
     */
    val emphasizedSlotCount: Int get() = when (this) {
        AutoBigThree -> 3
        AutoBigTwo, HeroPair,
        BigTwoStack, BigTwoStackRight, BigTwoStackBottom,
        TShape, TShapeInverted,
        LShape, LShapeTopRight, LShapeBottomLeft, LShapeBottomRight -> 2
        else -> 1
    }

    /** Stable string key; matches termtastic's `LAYOUTS` keys for cross-app
     *  consistency in serialization, telemetry, and tooling. */
    val key: String get() = when (this) {
        Auto -> "auto"
        Grid -> "grid"
        Columns -> "columns"
        Rows -> "rows"
        HeroLeft -> "hero-left"
        HeroRight -> "hero-right"
        HeroTop -> "hero-top"
        HeroBottom -> "hero-bottom"
        SplitHorizontal -> "split-h"
        SplitVertical -> "split-v"
        SidebarLeft -> "sidebar-left"
        SidebarRight -> "sidebar-right"
        SidebarTop -> "sidebar-top"
        SidebarBottom -> "sidebar-bottom"
        TShape -> "t-shape"
        TShapeInverted -> "t-shape-inv"
        LShape -> "l-shape"
        LShapeTopRight -> "l-shape-tr"
        LShapeBottomLeft -> "l-shape-bl"
        LShapeBottomRight -> "l-shape-br"
        BigTwoStack -> "big-2-stack"
        BigTwoStackRight -> "big-2-stack-right"
        BigTwoStackBottom -> "big-2-stack-bottom"
        AutoBigTwo -> "auto-big-2"
        AutoBigTwoRight -> "auto-big-2-right"
        AutoBigTwoTop -> "auto-big-2-top"
        AutoBigTwoBottom -> "auto-big-2-bottom"
        AutoBigThree -> "auto-big-3"
        HeroPair -> "hero-pair"
        HeroPairRight -> "hero-pair-right"
        HeroPairTop -> "hero-pair-top"
        HeroPairBottom -> "hero-pair-bottom"
        Custom -> "custom"
    }

    /** Human-readable label shown as a tooltip on the dropdown tile. */
    val label: String get() = when (this) {
        Auto -> "Auto"
        Grid -> "Grid"
        Columns -> "Equal columns"
        Rows -> "Equal rows"
        HeroLeft -> "Hero left"
        HeroRight -> "Hero right"
        HeroTop -> "Hero top"
        HeroBottom -> "Hero bottom"
        SplitHorizontal -> "Split horizontal"
        SplitVertical -> "Split vertical"
        SidebarLeft -> "Sidebar left"
        SidebarRight -> "Sidebar right"
        SidebarTop -> "Sidebar top"
        SidebarBottom -> "Sidebar bottom"
        TShape -> "T-shape"
        TShapeInverted -> "Inverted T"
        LShape -> "L-shape (top-left)"
        LShapeTopRight -> "L-shape (top-right)"
        LShapeBottomLeft -> "L-shape (bottom-left)"
        LShapeBottomRight -> "L-shape (bottom-right)"
        BigTwoStack -> "Big left + right stack"
        BigTwoStackRight -> "Big right + left stack"
        BigTwoStackBottom -> "Big bottom + top stack"
        AutoBigTwo -> "Auto (2 emphasized)"
        AutoBigTwoRight -> "Auto (2 emphasized, right)"
        AutoBigTwoTop -> "Auto (2 emphasized, top)"
        AutoBigTwoBottom -> "Auto (2 emphasized, bottom)"
        AutoBigThree -> "Auto (3 emphasized)"
        HeroPair -> "Hero pair"
        HeroPairRight -> "Hero pair (right)"
        HeroPairTop -> "Hero pair (top)"
        HeroPairBottom -> "Hero pair (bottom)"
        Custom -> "Custom"
    }

    companion object {
        /**
         * Resolves a preset by its [key]. Returns `null` for unknown
         * keys, including `"custom"` (apps shouldn't persist Custom as
         * an explicit choice — it's a mode, not a target).
         *
         * @param key string key as produced by [LayoutPreset.key].
         * @return the matching preset, or `null` if not found.
         */
        fun fromKey(key: String): LayoutPreset? =
            entries.firstOrNull { it.key == key }

        /** Subset of presets shown in the layout dropdown, in display order. */
        val DROPDOWN_ORDER: List<LayoutPreset> = listOf(
            Auto,
            AutoBigTwo, AutoBigTwoRight, AutoBigTwoTop, AutoBigTwoBottom,
            AutoBigThree,
            Grid, Columns, Rows,
            HeroLeft, HeroRight, HeroTop, HeroBottom,
            HeroPair, HeroPairRight, HeroPairTop, HeroPairBottom,
            SplitHorizontal, SplitVertical,
            SidebarLeft, SidebarRight, SidebarTop, SidebarBottom,
            TShape, TShapeInverted,
            LShape, LShapeTopRight, LShapeBottomLeft, LShapeBottomRight,
            BigTwoStack, BigTwoStackRight, BigTwoStackBottom,
        )
    }
}

/**
 * Mirror of termtastic's `LayoutMenu.computeLayout`: produces the slot
 * rectangles for [preset] given [n] panes. Slot 0 is always the primary
 * (the position the active pane lands in). Used by both the dropdown
 * miniatures (rendered as scaled SVG rects) and by hosts that apply the
 * layout to their pane list.
 *
 * Keeping a single source of truth means the preview the user sees and
 * the result they get match — no drift between the miniature and the
 * applied layout.
 *
 * @param preset which layout family to compute boxes for. [LayoutPreset.Custom]
 *   is a sentinel — no preset is driving — so it returns an empty list.
 * @param n      number of panes; non-positive returns an empty list,
 *   `1` collapses every preset to a single full-bleed box.
 * @return list of [n] rectangles, slot 0 first.
 */
internal fun computeLayoutBoxes(preset: LayoutPreset, n: Int): List<LayoutBox> {
    if (preset == LayoutPreset.Custom) return emptyList()
    if (n <= 0) return emptyList()
    if (n == 1) return listOf(LayoutBox(0.0, 0.0, 1.0, 1.0))
    return when (preset) {
        LayoutPreset.Auto -> autoBoxes(n)

        LayoutPreset.HeroLeft -> listOf(LayoutBox(0.0, 0.0, 0.65, 1.0)) +
            equalStrip(n - 1, 0.65, 0.0, 0.35, 1.0, horizontal = false)
        LayoutPreset.HeroRight -> listOf(LayoutBox(0.35, 0.0, 0.65, 1.0)) +
            equalStrip(n - 1, 0.0, 0.0, 0.35, 1.0, horizontal = false)
        LayoutPreset.HeroTop -> listOf(LayoutBox(0.0, 0.0, 1.0, 0.65)) +
            equalStrip(n - 1, 0.0, 0.65, 1.0, 0.35, horizontal = true)
        LayoutPreset.HeroBottom -> listOf(LayoutBox(0.0, 0.35, 1.0, 0.65)) +
            equalStrip(n - 1, 0.0, 0.0, 1.0, 0.35, horizontal = true)

        LayoutPreset.SplitHorizontal -> listOf(LayoutBox(0.0, 0.0, 0.50, 1.0)) +
            equalStrip(n - 1, 0.50, 0.0, 0.50, 1.0, horizontal = false)
        LayoutPreset.SplitVertical -> listOf(LayoutBox(0.0, 0.0, 1.0, 0.50)) +
            equalStrip(n - 1, 0.0, 0.50, 1.0, 0.50, horizontal = true)

        LayoutPreset.SidebarLeft -> listOf(LayoutBox(0.25, 0.0, 0.75, 1.0)) +
            equalStrip(n - 1, 0.0, 0.0, 0.25, 1.0, horizontal = false)
        LayoutPreset.SidebarRight -> listOf(LayoutBox(0.0, 0.0, 0.75, 1.0)) +
            equalStrip(n - 1, 0.75, 0.0, 0.25, 1.0, horizontal = false)
        LayoutPreset.SidebarTop -> listOf(LayoutBox(0.0, 0.25, 1.0, 0.75)) +
            equalStrip(n - 1, 0.0, 0.0, 1.0, 0.25, horizontal = true)
        LayoutPreset.SidebarBottom -> listOf(LayoutBox(0.0, 0.0, 1.0, 0.75)) +
            equalStrip(n - 1, 0.0, 0.75, 1.0, 0.25, horizontal = true)

        LayoutPreset.TShape -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.70, 1.0),
                LayoutBox(0.70, 0.0, 0.30, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.0, 0.70, 0.70))
                add(LayoutBox(0.70, 0.0, 0.30, 0.70))
                addAll(equalStrip(n - 2, 0.0, 0.70, 1.0, 0.30, horizontal = true))
            }
        }
        LayoutPreset.TShapeInverted -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.70, 1.0),
                LayoutBox(0.70, 0.0, 0.30, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.30, 0.70, 0.70))
                add(LayoutBox(0.70, 0.30, 0.30, 0.70))
                addAll(equalStrip(n - 2, 0.0, 0.0, 1.0, 0.30, horizontal = true))
            }
        }

        LayoutPreset.LShape -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.65, 1.0),
                LayoutBox(0.65, 0.0, 0.35, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.0, 0.65, 0.65))
                add(LayoutBox(0.65, 0.0, 0.35, 1.0))
                addAll(equalStrip(n - 2, 0.0, 0.65, 0.65, 0.35, horizontal = true))
            }
        }
        LayoutPreset.LShapeTopRight -> when (n) {
            2 -> listOf(
                LayoutBox(0.35, 0.0, 0.65, 1.0),
                LayoutBox(0.0, 0.0, 0.35, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.35, 0.0, 0.65, 0.65))
                add(LayoutBox(0.0, 0.0, 0.35, 1.0))
                addAll(equalStrip(n - 2, 0.35, 0.65, 0.65, 0.35, horizontal = true))
            }
        }
        LayoutPreset.LShapeBottomLeft -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.65, 1.0),
                LayoutBox(0.65, 0.0, 0.35, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.35, 0.65, 0.65))
                add(LayoutBox(0.65, 0.0, 0.35, 1.0))
                addAll(equalStrip(n - 2, 0.0, 0.0, 0.65, 0.35, horizontal = true))
            }
        }
        LayoutPreset.LShapeBottomRight -> when (n) {
            2 -> listOf(
                LayoutBox(0.35, 0.0, 0.65, 1.0),
                LayoutBox(0.0, 0.0, 0.35, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.35, 0.35, 0.65, 0.65))
                add(LayoutBox(0.0, 0.0, 0.35, 1.0))
                addAll(equalStrip(n - 2, 0.35, 0.0, 0.65, 0.35, horizontal = true))
            }
        }

        LayoutPreset.BigTwoStack -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.60, 1.0),
                LayoutBox(0.60, 0.0, 0.40, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.0, 0.60, 1.0))
                add(LayoutBox(0.60, 0.0, 0.40, 0.60))
                addAll(equalStrip(n - 2, 0.60, 0.60, 0.40, 0.40, horizontal = false))
            }
        }
        LayoutPreset.BigTwoStackRight -> when (n) {
            2 -> listOf(
                LayoutBox(0.40, 0.0, 0.60, 1.0),
                LayoutBox(0.0, 0.0, 0.40, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.40, 0.0, 0.60, 1.0))
                add(LayoutBox(0.0, 0.0, 0.40, 0.60))
                addAll(equalStrip(n - 2, 0.0, 0.60, 0.40, 0.40, horizontal = false))
            }
        }
        LayoutPreset.BigTwoStackBottom -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.40, 1.0, 0.60),
                LayoutBox(0.0, 0.0, 1.0, 0.40),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.40, 1.0, 0.60),)
                add(LayoutBox(0.0, 0.0, 0.60, 0.40))
                addAll(equalStrip(n - 2, 0.60, 0.0, 0.40, 0.40, horizontal = true))
            }
        }

        LayoutPreset.AutoBigTwo -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.60, 1.0),
                LayoutBox(0.60, 0.0, 0.40, 1.0),
            )
            3 -> listOf(
                // Identical shape to Auto-3: primary 60% full-height,
                // slot 1 top-right 40%×50%, slot 2 bottom-right 40%×50%.
                LayoutBox(0.0, 0.0, 0.60, 1.0),
                LayoutBox(0.60, 0.0, 0.40, 0.50),
                LayoutBox(0.60, 0.50, 0.40, 0.50),
            )
            else -> buildList {
                // Primary 60%×100%, secondary 40%×50% top-right, rest
                // equal-stack the bottom-right 40%×50% strip.
                add(LayoutBox(0.0, 0.0, 0.60, 1.0))
                add(LayoutBox(0.60, 0.0, 0.40, 0.50))
                addAll(equalStrip(n - 2, 0.60, 0.50, 0.40, 0.50, horizontal = false))
            }
        }
        LayoutPreset.AutoBigTwoRight -> when (n) {
            2 -> listOf(
                LayoutBox(0.40, 0.0, 0.60, 1.0),
                LayoutBox(0.0, 0.0, 0.40, 1.0),
            )
            3 -> listOf(
                LayoutBox(0.40, 0.0, 0.60, 1.0),
                LayoutBox(0.0, 0.0, 0.40, 0.50),
                LayoutBox(0.0, 0.50, 0.40, 0.50),
            )
            else -> buildList {
                add(LayoutBox(0.40, 0.0, 0.60, 1.0))
                add(LayoutBox(0.0, 0.0, 0.40, 0.50))
                addAll(equalStrip(n - 2, 0.0, 0.50, 0.40, 0.50, horizontal = false))
            }
        }
        LayoutPreset.AutoBigTwoTop -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 1.0, 0.60),
                LayoutBox(0.0, 0.60, 1.0, 0.40),
            )
            3 -> listOf(
                LayoutBox(0.0, 0.0, 1.0, 0.60),
                LayoutBox(0.0, 0.60, 0.50, 0.40),
                LayoutBox(0.50, 0.60, 0.50, 0.40),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.0, 1.0, 0.60))
                add(LayoutBox(0.0, 0.60, 0.50, 0.40))
                addAll(equalStrip(n - 2, 0.50, 0.60, 0.50, 0.40, horizontal = true))
            }
        }
        LayoutPreset.AutoBigTwoBottom -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.40, 1.0, 0.60),
                LayoutBox(0.0, 0.0, 1.0, 0.40),
            )
            3 -> listOf(
                LayoutBox(0.0, 0.40, 1.0, 0.60),
                LayoutBox(0.0, 0.0, 0.50, 0.40),
                LayoutBox(0.50, 0.0, 0.50, 0.40),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.40, 1.0, 0.60))
                add(LayoutBox(0.0, 0.0, 0.50, 0.40))
                addAll(equalStrip(n - 2, 0.50, 0.0, 0.50, 0.40, horizontal = true))
            }
        }
        LayoutPreset.AutoBigThree -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.50, 1.0),
                LayoutBox(0.50, 0.0, 0.50, 1.0),
            )
            3 -> listOf(
                // Slots 2 and 3 stack top-right; bottom-right left
                // empty since there's no rest. Primary keeps half.
                LayoutBox(0.0, 0.0, 0.50, 1.0),
                LayoutBox(0.50, 0.0, 0.25, 1.0),
                LayoutBox(0.75, 0.0, 0.25, 1.0),
            )
            4 -> listOf(
                // 2 and 3 top-right, 4 fills the bottom-right strip.
                LayoutBox(0.0, 0.0, 0.50, 1.0),
                LayoutBox(0.50, 0.0, 0.25, 0.50),
                LayoutBox(0.75, 0.0, 0.25, 0.50),
                LayoutBox(0.50, 0.50, 0.50, 0.50),
            )
            else -> buildList {
                // Primary 50%×100%, slots 2/3 stacked top-right at
                // 25%×50% each, rest equal-strip across the bottom
                // right 50%×50%.
                add(LayoutBox(0.0, 0.0, 0.50, 1.0))
                add(LayoutBox(0.50, 0.0, 0.25, 0.50))
                add(LayoutBox(0.75, 0.0, 0.25, 0.50))
                addAll(equalStrip(n - 3, 0.50, 0.50, 0.50, 0.50, horizontal = true))
            }
        }
        LayoutPreset.HeroPair -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 0.55, 1.0),
                LayoutBox(0.55, 0.0, 0.45, 1.0),
            )
            else -> buildList {
                // Primary 55%×100% left, secondary 45%×40% top-right,
                // rest equal-stack the 45%×60% bottom-right.
                add(LayoutBox(0.0, 0.0, 0.55, 1.0))
                add(LayoutBox(0.55, 0.0, 0.45, 0.40))
                addAll(equalStrip(n - 2, 0.55, 0.40, 0.45, 0.60, horizontal = false))
            }
        }
        LayoutPreset.HeroPairRight -> when (n) {
            2 -> listOf(
                LayoutBox(0.45, 0.0, 0.55, 1.0),
                LayoutBox(0.0, 0.0, 0.45, 1.0),
            )
            else -> buildList {
                add(LayoutBox(0.45, 0.0, 0.55, 1.0))
                add(LayoutBox(0.0, 0.0, 0.45, 0.40))
                addAll(equalStrip(n - 2, 0.0, 0.40, 0.45, 0.60, horizontal = false))
            }
        }
        LayoutPreset.HeroPairTop -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.0, 1.0, 0.55),
                LayoutBox(0.0, 0.55, 1.0, 0.45),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.0, 1.0, 0.55))
                add(LayoutBox(0.0, 0.55, 0.40, 0.45))
                addAll(equalStrip(n - 2, 0.40, 0.55, 0.60, 0.45, horizontal = true))
            }
        }
        LayoutPreset.HeroPairBottom -> when (n) {
            2 -> listOf(
                LayoutBox(0.0, 0.45, 1.0, 0.55),
                LayoutBox(0.0, 0.0, 1.0, 0.45),
            )
            else -> buildList {
                add(LayoutBox(0.0, 0.45, 1.0, 0.55))
                add(LayoutBox(0.0, 0.0, 0.40, 0.45))
                addAll(equalStrip(n - 2, 0.40, 0.0, 0.60, 0.45, horizontal = true))
            }
        }

        LayoutPreset.Columns -> equalColumns(n)
        LayoutPreset.Rows -> equalRows(n)
        LayoutPreset.Grid -> {
            // even tiling with primary at top-left.
            val cols = kotlin.math.ceil(kotlin.math.sqrt(n.toDouble())).toInt().coerceAtLeast(1)
            val rows = kotlin.math.ceil(n.toDouble() / cols).toInt().coerceAtLeast(1)
            val w = 1.0 / cols
            val h = 1.0 / rows
            (0 until n).map { i ->
                val r = i / cols
                val c = i % cols
                LayoutBox(c * w, r * h, w, h)
            }
        }

        LayoutPreset.Custom -> emptyList()
    }
}

/**
 * Geometry for the [LayoutPreset.Auto] preset. Picks a sensible shape
 * based purely on pane count, with the primary (slot 0) always getting
 * the largest box. The output is intended to be combined with a
 * [GridSpec] for visual snap; without one, the boxes use the raw
 * fractions documented below.
 *
 * Counts:
 * - 1   → full-bleed
 * - 2   → 50/50 horizontal split
 * - 3   → primary 60% full-height + 2 stacked on the right 40%
 * - 4   → primary 60% full-height + 3 stacked on the right 40%
 * - 5   → primary 60% full-height + 4 stacked on the right 40%
 * - 6   → 3×2 grid; primary at top-left
 * - ≥7  → square-ish grid `cols = ceil(sqrt(n))`, `rows = ceil(n/cols)`,
 *         primary at top-left
 *
 * Keeping the geometry simple and pure-of-`n` makes Auto's reflow
 * deterministic — re-tiling on every pane add/remove never produces a
 * surprising layout.
 *
 * @param n number of panes; assumed `>= 2` (callers handle 0 and 1).
 * @return list of [n] boxes, slot 0 (largest) first.
 */
private fun autoBoxes(n: Int): List<LayoutBox> {
    return when (n) {
        2 -> listOf(
            LayoutBox(0.0, 0.0, 0.50, 1.0),
            LayoutBox(0.50, 0.0, 0.50, 1.0),
        )
        in 3..5 -> buildList {
            add(LayoutBox(0.0, 0.0, 0.60, 1.0))
            addAll(equalStrip(n - 1, 0.60, 0.0, 0.40, 1.0, horizontal = false))
        }
        6 -> {
            // 3 cols × 2 rows; primary in top-left
            val w = 1.0 / 3
            val h = 1.0 / 2
            (0 until 6).map { i ->
                val r = i / 3
                val c = i % 3
                LayoutBox(c * w, r * h, w, h)
            }
        }
        else -> {
            val cols = kotlin.math.ceil(kotlin.math.sqrt(n.toDouble())).toInt().coerceAtLeast(1)
            val rows = kotlin.math.ceil(n.toDouble() / cols).toInt().coerceAtLeast(1)
            val w = 1.0 / cols
            val h = 1.0 / rows
            (0 until n).map { i ->
                val r = i / cols
                val c = i % cols
                LayoutBox(c * w, r * h, w, h)
            }
        }
    }
}

/** Equally-sized horizontal or vertical strip filling the given rectangle. */
private fun equalStrip(
    count: Int,
    ox: Double,
    oy: Double,
    sx: Double,
    sy: Double,
    horizontal: Boolean,
): List<LayoutBox> {
    if (count <= 0) return emptyList()
    val out = ArrayList<LayoutBox>(count)
    if (horizontal) {
        val bw = sx / count
        for (i in 0 until count) out.add(LayoutBox(ox + i * bw, oy, bw, sy))
    } else {
        val bh = sy / count
        for (i in 0 until count) out.add(LayoutBox(ox, oy + i * bh, sx, bh))
    }
    return out
}

/** N equal-width columns, primary at index 0 (left edge). */
private fun equalColumns(n: Int): List<LayoutBox> = (0 until n).map { i ->
    val w = 1.0 / n
    LayoutBox(i * w, 0.0, w, 1.0)
}

/** N equal-height rows, primary at index 0 (top edge). */
private fun equalRows(n: Int): List<LayoutBox> = (0 until n).map { i ->
    val h = 1.0 / n
    LayoutBox(0.0, i * h, 1.0, h)
}
